package com.lx.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-10-19T15:31:23.004+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.bsoft.com.cn/webservices/", name = "ServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceHttpPost {

    @WebMethod(operationName = "GetITFPatinfo_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatinfoOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "MzybFysc_DoAll")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String mzybFyscDoAll(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Getygxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getygxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetCwbbBbmx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getCwbbBbmx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetInfectionReport")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getInfectionReport(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Ot_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatOtIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyjsYbjsxm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyjsYbjsxm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFImformation")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFImformation();

    @WebMethod(operationName = "GetMzBrxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Xys_SendReservedMSM")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String xysSendReservedMSM(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Mzhm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListMzhm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 龙华分院获取检验单信息
     */
    @WebMethod(operationName = "GetLisList_HisToLis")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListHisToLis(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBasy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBasy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetYpxxList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYpxxList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetYspb")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYspb(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySssqxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySssqxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_GetPatientsInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisGetPatientsInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "ReadLog")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String readLog();

    @WebMethod(operationName = "GetPacsInfo_zy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getPacsInfoZy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Xk_InsertPxtz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String xkInsertPxtz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetGyslyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getGyslyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "SaveText")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String saveText(
            @WebParam(partName = "FileName", name = "FileName", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String fileName,
            @WebParam(partName = "CodeType", name = "CodeType", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String codeType,
            @WebParam(partName = "TextValue", name = "TextValue", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String textValue
    );

    @WebMethod(operationName = "GetLisList_Tmbh_Zy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListTmbhZy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Bc_GetReportInfo_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String bcGetReportInfoMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Admission_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatAdmissionIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Yhsfrz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String yhsfrz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetDoctorList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getDoctorList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_ReWjz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisReWjz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "ReMzjc_CTMR_Yysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reMzjcCTMRYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFOt_Type")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFOtType();

    @WebMethod(operationName = "GetZyjcYysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyjcYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzBrxx_Sfzh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxxSfzh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzBrxx_Ny")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxxNy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertFymx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertFymx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDrug_Move_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrugMoveOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMztgYydh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMztgYydh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjc_CTMR_Yyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcCTMRYyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDrug_Classify")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrugClassify();

    @WebMethod(operationName = "GetLisCqsh_Tmbh_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisCqshTmbhMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetKsysSdpbmx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getKsysSdpbmx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetJclx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getJclx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Getyyxxbysqdxh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getyyxxbysqdxh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySsyyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySsyyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CreateBrda")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createBrda(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Pacs_GetReportInfo_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String pacsGetReportInfoMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 取消挂号支付
     */
    @WebMethod(operationName = "CancelMzgh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelMzgh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Get_Smtz")
    @WebResult(name = "int", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public int getSmtz(
            @WebParam(partName = "Code", name = "Code", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String code
    );

    @WebMethod(operationName = "GetKshy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getKshy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Fphm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListFphm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "UpdatePyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String updatePyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFCharges_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFChargesOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyFymx_Ksdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyFymxKsdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzBrxx_flk")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxxFlk(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetComboAndItemsInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getComboAndItemsInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFSpec")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFSpec();

    @WebMethod(operationName = "GetITFPat_Admission_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatAdmissionOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyjsJsxm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyjsJsxm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetSfxmList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getSfxmList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertZybrYjjk")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertZybrYjjk(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetGyslyxx_mx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getGyslyxxMx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Cyrq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxCyrq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 生成挂号关联费用
     */
    @WebMethod(operationName = "GetMustFeeItem")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMustFeeItem(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFLis_Result_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFLisResultOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetKstc")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getKstc(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetLisInfo_zy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisInfoZy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjc_CTMR_Sqdxx_Sqdxh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcCTMRSqdxxSqdxh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDrug")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrug();

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String test(
            @WebParam(partName = "mcardNo", name = "mcardNo", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String mcardNo
    );

    @WebMethod(operationName = "GetJyxmList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getJyxmList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "ReMzjySqdzt")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reMzjySqdzt(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_InsertWjz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisInsertWjz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_V_Hais_Pathogen")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisVHaisPathogen(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ackRefundMzReg(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzdmList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzdmList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFEmployee_Postition")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFEmployeePostition();

    /**
     * 挂号预约查询
     */
    @WebMethod(operationName = "GetYyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Character_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatCharacterIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetDoctorType")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getDoctorType(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Bl_GetReportInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String blGetReportInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFAllergy_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFAllergyIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertSmtz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertSmtz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CancelMzjcYysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelMzjcYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CancelYyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelYyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_V_Hais_AntiName")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisVHaisAntiName(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrJsxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrJsxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "ReMzjcYysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reMzjcYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetYshy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYshy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzBrxx_Fphm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxxFphm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyFymx_Tmbh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyFymxTmbh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Ecg_GetReportInfo_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ecgGetReportInfoMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertCffyzs")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertCffyzs(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetHospitalId")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getHospitalId();

    @WebMethod(operationName = "ReZyjcYysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reZyjcYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_GetReportInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisGetReportInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFRcpt_Policy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFRcptPolicy();

    @WebMethod(operationName = "GetZyBrxx_Rycs")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxRycs(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Get_dzxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getDzxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Mzhm_Rq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListMzhmRq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetGhks")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getGhks(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFEmployee")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFEmployee();

    @WebMethod(operationName = "GetSdpb")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getSdpb(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBlnr_cyrq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBlnrCyrq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 门诊病人处方支付
     */
    @WebMethod(operationName = "MzChuFangZf")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String mzChuFangZf(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CreateMzgh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createMzgh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 获取检查危机值信息
     */
    @WebMethod(operationName = "GetCriticalValue_MedicalTech")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getCriticalValueMedicalTech(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CA_CreateKey")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String caCreateKey();

    @WebMethod(operationName = "GetChuFangMx_Ny")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangMxNy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySsbr")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySsbr(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyXmsfmx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyXmsfmx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CreateBrdaMzgh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createBrdaMzgh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetCwbbList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getCwbbList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrZkjl")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrZkjl(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Cx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxCx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Xk_GetBarcode")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String xkGetBarcode(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Brwd")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxBrwd(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrSmtzByZyhm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrSmtzByZyhm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetGysWpxxList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getGysWpxxList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjc_CTMR_Yysj")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcCTMRYysj(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "SzCa_LognCheck")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String szCaLognCheck(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetKspb")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getKspb(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "LogIn")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String logIn(
            @WebParam(partName = "logid", name = "logid", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String logid,
            @WebParam(partName = "password", name = "password", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String password
    );

    @WebMethod(operationName = "yb_SaveMZGH")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ybSaveMZGH(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzJzxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzJzxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Dnh_Rq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListDnhRq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Cyrq_WithoutJs")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxCyrqWithoutJs(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 银行支付
     */
    @WebMethod(operationName = "CreateBank")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createBank(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetBrxz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getBrxz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDrug_Move_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrugMoveIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFWard_Spec")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFWardSpec();

    @WebMethod(operationName = "GetITFPat_Patinfo_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatPatinfoIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "ReMzjcSqzx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reMzjcSqzx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CreateYyxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createYyxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrSmtz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrSmtz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyjsYbzfxm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyjsYbzfxm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Getyyxxbyksdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getyyxxbyksdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Kdks_Rq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListKdksRq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrxx_Dbz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrxxDbz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 传送危急值病人信息
     */
    @WebMethod(operationName = "GetCriticalValuesInfo_PatientInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getCriticalValuesInfoPatientInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "SzCa_ValidSign")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String szCaValidSign(
            @WebParam(partName = "as_pubkey", name = "as_pubkey", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String asPubkey,
            @WebParam(partName = "as_qmjg", name = "as_qmjg", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String asQmjg,
            @WebParam(partName = "as_qmyw", name = "as_qmyw", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String asQmyw,
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetDepartment")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getDepartment(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetLisList_Ksdm_Zy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListKsdmZy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Ecg_GetReportInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ecgGetReportInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetBqhy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getBqhy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyjsFymx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyjsFymx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetGhxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getGhxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDrug_Right_Limit")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrugRightLimit();

    @WebMethod(operationName = "GetITFDrug_Classify_Relation")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDrugClassifyRelation();

    @WebMethod(operationName = "Get_Signdata_Jcxx_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getSigndataJcxxMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPrescribe_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPrescribeIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetLisList_Mzhm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListMzhm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Diagnosis_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatDiagnosisOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBlList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBlList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "get_hisdatetime")
    @WebResult(name = "dateTime", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public javax.xml.datatype.XMLGregorianCalendar getHisdatetime();

    @WebMethod(operationName = "GetZybrxx_Dbzlb")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrxxDbzlb(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetYsdlks")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYsdlks(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 取消处方支付
     */
    @WebMethod(operationName = "CancelMzChuFangZf")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelMzChuFangZf(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertSsap")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertSsap(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Pacs_GetReportInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String pacsGetReportInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Hsrq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxHsrq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "MzybFysc")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String mzybFysc(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetYbdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getYbdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Sfzh_Rq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListSfzhRq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "yb_refundMZGH")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ybRefundMZGH(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetLisInfo_mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisInfoMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrZyzd")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrZyzd(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Cancel_CTMR_Yysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelCTMRYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CA_VerifySignedHash")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String caVerifySignedHash(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "SetCwbbWcbz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String setCwbbWcbz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyYrfyqd")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyYrfyqd(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "SetMySoapHeader")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String setMySoapHeader(
            @WebParam(partName = "userName", name = "userName", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String userName,
            @WebParam(partName = "passWord", name = "passWord", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String passWord,
            @WebParam(partName = "Yyid", name = "Yyid", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String yyid
    );

    /**
     * 取门诊病人处方列表信息(按处方识别)
     */
    @WebMethod(operationName = "GetChuFangList_Cfsb")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListCfsb(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFAdmin_Route")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFAdminRoute();

    @WebMethod(operationName = "yb_refundMZInsurance")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ybRefundMZInsurance(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySsxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySsxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDiagnosis_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDiagnosisIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Ksdm_flk")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxKsdmFlk(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ackRefundReg(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFDiagnosis")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFDiagnosis();

    @WebMethod(operationName = "GetPacsInfo_mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getPacsInfoMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "yb_settleMZInsurance")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ybSettleMZInsurance(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CA_HashAndSign")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String caHashAndSign(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetUserId")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getUserId();

    @WebMethod(operationName = "GetLisList_Tmbh_Mz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListTmbhMz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFCharges_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFChargesIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetLisList_Zyhm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListZyhm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetComboForItemList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getComboForItemList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjc_CTMR_Sqdxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcCTMRSqdxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZySqssmc")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZySqssmc(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CancelMzyfLed")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String cancelMzyfLed(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Re_Ktf")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String reKtf(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFWard")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFWard();

    @WebMethod(operationName = "Bc_GetReportInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String bcGetReportInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPrescribe_Type")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPrescribeType();

    @WebMethod(operationName = "GetMzBrxx_sqdxh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzBrxxSqdxh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "InsertSsfy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String insertSsfy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetBasysj_ssxx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getBasysjSsxx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 龙华分院按照执行科室获取检验单信息
     */
    @WebMethod(operationName = "GetLisList_HisToLis_Ksdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getLisListHisToLisKsdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBlnr")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBlnr(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBrxx_Ksdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBrxxKsdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjcYysq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcYysq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzTmbh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzTmbh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 取门诊病人处方列表信息
     */
    @WebMethod(operationName = "GetChuFangList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_GetCTSpecimen")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisGetCTSpecimen(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZybrSmtzForAll")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZybrSmtzForAll(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetChuFangList_Ny_Kfrq")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangListNyKfrq(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "MzybMzdj")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String mzybMzdj(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Dz_Ml_Mu002")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String dzMlMu002(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetSsdmList")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getSsdmList(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Lis_GetResultInfo")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String lisGetResultInfo(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Dz_Ml_Mu001")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String dzMlMu001(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 重复用药提醒
     */
    @WebMethod(operationName = "MedRepeatedUse")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String medRepeatedUse(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Dz_Ml_Mu003")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String dzMlMu003(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    /**
     * 取门诊病人处方明细
     */
    @WebMethod(operationName = "GetChuFangMx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getChuFangMx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Change_Spec_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatChangeSpecIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyBqyz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyBqyz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetBqhyYzdm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getBqhyYzdm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPrescibe_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPrescibeOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFEmployee_Spec")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFEmployeeSpec();

    @WebMethod(operationName = "GetBqgyByJzwz")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getBqgyByJzwz(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFPat_Ot_Apply_Ip")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFPatOtApplyIp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetMzjcYysq_Sqdxh")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getMzjcYysqSqdxh(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetZyFymx")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getZyFymx(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "GetITFAllergy_Op")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String getITFAllergyOp(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Ss_GetReportInfo_Zy")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String ssGetReportInfoZy(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "Check_CTMR_Cancel_Status")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String checkCTMRCancelStatus(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );

    @WebMethod(operationName = "CreateJzhm")
    @WebResult(name = "string", targetNamespace = "http://www.bsoft.com.cn/webservices/", partName = "Body")
    public String createJzhm(
            @WebParam(partName = "inXML", name = "inXML", targetNamespace = "http://www.bsoft.com.cn/webservices/")
            String inXML
    );
}
