
package com.lx.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-10-19T15:31:22.947+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class ServiceSoap_ServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.bsoft.com.cn/webservices/", "Service");

    private ServiceSoap_ServiceSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap12();  
        
        {
        System.out.println("Invoking getITFPatinfoOp...");
        String _getITFPatinfoOp_inXML = "";
        String _getITFPatinfoOp__return = port.getITFPatinfoOp(_getITFPatinfoOp_inXML);
        System.out.println("getITFPatinfoOp.result=" + _getITFPatinfoOp__return);


        }
        {
        System.out.println("Invoking mzybFyscDoAll...");
        String _mzybFyscDoAll_inXML = "";
        String _mzybFyscDoAll__return = port.mzybFyscDoAll(_mzybFyscDoAll_inXML);
        System.out.println("mzybFyscDoAll.result=" + _mzybFyscDoAll__return);


        }
        {
        System.out.println("Invoking getygxx...");
        String _getygxx_inXML = "";
        String _getygxx__return = port.getygxx(_getygxx_inXML);
        System.out.println("getygxx.result=" + _getygxx__return);


        }
        {
        System.out.println("Invoking getCwbbBbmx...");
        String _getCwbbBbmx_inXML = "";
        String _getCwbbBbmx__return = port.getCwbbBbmx(_getCwbbBbmx_inXML);
        System.out.println("getCwbbBbmx.result=" + _getCwbbBbmx__return);


        }
        {
        System.out.println("Invoking getInfectionReport...");
        String _getInfectionReport_inXML = "";
        String _getInfectionReport__return = port.getInfectionReport(_getInfectionReport_inXML);
        System.out.println("getInfectionReport.result=" + _getInfectionReport__return);


        }
        {
        System.out.println("Invoking getITFPatOtIp...");
        String _getITFPatOtIp_inXML = "";
        String _getITFPatOtIp__return = port.getITFPatOtIp(_getITFPatOtIp_inXML);
        System.out.println("getITFPatOtIp.result=" + _getITFPatOtIp__return);


        }
        {
        System.out.println("Invoking getZyjsYbjsxm...");
        String _getZyjsYbjsxm_inXML = "";
        String _getZyjsYbjsxm__return = port.getZyjsYbjsxm(_getZyjsYbjsxm_inXML);
        System.out.println("getZyjsYbjsxm.result=" + _getZyjsYbjsxm__return);


        }
        {
        System.out.println("Invoking getITFImformation...");
        String _getITFImformation__return = port.getITFImformation();
        System.out.println("getITFImformation.result=" + _getITFImformation__return);


        }
        {
        System.out.println("Invoking getMzBrxx...");
        String _getMzBrxx_inXML = "";
        String _getMzBrxx__return = port.getMzBrxx(_getMzBrxx_inXML);
        System.out.println("getMzBrxx.result=" + _getMzBrxx__return);


        }
        {
        System.out.println("Invoking xysSendReservedMSM...");
        String _xysSendReservedMSM_inXML = "";
        String _xysSendReservedMSM__return = port.xysSendReservedMSM(_xysSendReservedMSM_inXML);
        System.out.println("xysSendReservedMSM.result=" + _xysSendReservedMSM__return);


        }
        {
        System.out.println("Invoking getChuFangListMzhm...");
        String _getChuFangListMzhm_inXML = "";
        String _getChuFangListMzhm__return = port.getChuFangListMzhm(_getChuFangListMzhm_inXML);
        System.out.println("getChuFangListMzhm.result=" + _getChuFangListMzhm__return);


        }
        {
        System.out.println("Invoking getLisListHisToLis...");
        String _getLisListHisToLis_inXML = "";
        String _getLisListHisToLis__return = port.getLisListHisToLis(_getLisListHisToLis_inXML);
        System.out.println("getLisListHisToLis.result=" + _getLisListHisToLis__return);


        }
        {
        System.out.println("Invoking getZyBasy...");
        String _getZyBasy_inXML = "";
        String _getZyBasy__return = port.getZyBasy(_getZyBasy_inXML);
        System.out.println("getZyBasy.result=" + _getZyBasy__return);


        }
        {
        System.out.println("Invoking getYpxxList...");
        String _getYpxxList_inXML = "";
        String _getYpxxList__return = port.getYpxxList(_getYpxxList_inXML);
        System.out.println("getYpxxList.result=" + _getYpxxList__return);


        }
        {
        System.out.println("Invoking getYspb...");
        String _getYspb_inXML = "";
        String _getYspb__return = port.getYspb(_getYspb_inXML);
        System.out.println("getYspb.result=" + _getYspb__return);


        }
        {
        System.out.println("Invoking getZySssqxx...");
        String _getZySssqxx_inXML = "";
        String _getZySssqxx__return = port.getZySssqxx(_getZySssqxx_inXML);
        System.out.println("getZySssqxx.result=" + _getZySssqxx__return);


        }
        {
        System.out.println("Invoking lisGetPatientsInfo...");
        String _lisGetPatientsInfo_inXML = "";
        String _lisGetPatientsInfo__return = port.lisGetPatientsInfo(_lisGetPatientsInfo_inXML);
        System.out.println("lisGetPatientsInfo.result=" + _lisGetPatientsInfo__return);


        }
        {
        System.out.println("Invoking readLog...");
        String _readLog__return = port.readLog();
        System.out.println("readLog.result=" + _readLog__return);


        }
        {
        System.out.println("Invoking getPacsInfoZy...");
        String _getPacsInfoZy_inXML = "";
        String _getPacsInfoZy__return = port.getPacsInfoZy(_getPacsInfoZy_inXML);
        System.out.println("getPacsInfoZy.result=" + _getPacsInfoZy__return);


        }
        {
        System.out.println("Invoking xkInsertPxtz...");
        String _xkInsertPxtz_inXML = "";
        String _xkInsertPxtz__return = port.xkInsertPxtz(_xkInsertPxtz_inXML);
        System.out.println("xkInsertPxtz.result=" + _xkInsertPxtz__return);


        }
        {
        System.out.println("Invoking getGyslyxx...");
        String _getGyslyxx_inXML = "";
        String _getGyslyxx__return = port.getGyslyxx(_getGyslyxx_inXML);
        System.out.println("getGyslyxx.result=" + _getGyslyxx__return);


        }
        {
        System.out.println("Invoking saveText...");
        String _saveText_fileName = "";
        String _saveText_codeType = "";
        String _saveText_textValue = "";
        String _saveText__return = port.saveText(_saveText_fileName, _saveText_codeType, _saveText_textValue);
        System.out.println("saveText.result=" + _saveText__return);


        }
        {
        System.out.println("Invoking getLisListTmbhZy...");
        String _getLisListTmbhZy_inXML = "";
        String _getLisListTmbhZy__return = port.getLisListTmbhZy(_getLisListTmbhZy_inXML);
        System.out.println("getLisListTmbhZy.result=" + _getLisListTmbhZy__return);


        }
        {
        System.out.println("Invoking bcGetReportInfoMz...");
        String _bcGetReportInfoMz_inXML = "";
        String _bcGetReportInfoMz__return = port.bcGetReportInfoMz(_bcGetReportInfoMz_inXML);
        System.out.println("bcGetReportInfoMz.result=" + _bcGetReportInfoMz__return);


        }
        {
        System.out.println("Invoking getResultInfo...");
        String _getResultInfo_visituser = "";
        String _getResultInfo_passwd = "";
        String _getResultInfo_personName = "";
        String _getResultInfo_idCard = "";
        String _getResultInfo_insuranceCard = "";
        String _getResultInfo_mediaCard = "";
        String _getResultInfo_type = "";
        String _getResultInfo_itemCode = "";
        String _getResultInfo_daterange = "";
        Integer _getResultInfo_flagVal = null;
        javax.xml.ws.Holder<Integer> _getResultInfo_flag = new javax.xml.ws.Holder<Integer>(_getResultInfo_flagVal);
        String _getResultInfo_msgVal = "";
        javax.xml.ws.Holder<String> _getResultInfo_msg = new javax.xml.ws.Holder<String>(_getResultInfo_msgVal);
        Integer _getResultInfo_risCountVal = null;
        javax.xml.ws.Holder<Integer> _getResultInfo_risCount = new javax.xml.ws.Holder<Integer>(_getResultInfo_risCountVal);
        Integer _getResultInfo_labCountVal = null;
        javax.xml.ws.Holder<Integer> _getResultInfo_labCount = new javax.xml.ws.Holder<Integer>(_getResultInfo_labCountVal);
        javax.xml.ws.Holder<String> _getResultInfo_getResultInfoResult = new javax.xml.ws.Holder<String>();
        port.getResultInfo(_getResultInfo_visituser, _getResultInfo_passwd, _getResultInfo_personName, _getResultInfo_idCard, _getResultInfo_insuranceCard, _getResultInfo_mediaCard, _getResultInfo_type, _getResultInfo_itemCode, _getResultInfo_daterange, _getResultInfo_flag, _getResultInfo_msg, _getResultInfo_risCount, _getResultInfo_labCount, _getResultInfo_getResultInfoResult);

        System.out.println("getResultInfo._getResultInfo_flag=" + _getResultInfo_flag.value);
        System.out.println("getResultInfo._getResultInfo_msg=" + _getResultInfo_msg.value);
        System.out.println("getResultInfo._getResultInfo_risCount=" + _getResultInfo_risCount.value);
        System.out.println("getResultInfo._getResultInfo_labCount=" + _getResultInfo_labCount.value);
        System.out.println("getResultInfo._getResultInfo_getResultInfoResult=" + _getResultInfo_getResultInfoResult.value);

        }
        {
        System.out.println("Invoking getITFPatAdmissionIp...");
        String _getITFPatAdmissionIp_inXML = "";
        String _getITFPatAdmissionIp__return = port.getITFPatAdmissionIp(_getITFPatAdmissionIp_inXML);
        System.out.println("getITFPatAdmissionIp.result=" + _getITFPatAdmissionIp__return);


        }
        {
        System.out.println("Invoking yhsfrz...");
        String _yhsfrz_inXML = "";
        String _yhsfrz__return = port.yhsfrz(_yhsfrz_inXML);
        System.out.println("yhsfrz.result=" + _yhsfrz__return);


        }
        {
        System.out.println("Invoking getDoctorList...");
        String _getDoctorList_inXML = "";
        String _getDoctorList__return = port.getDoctorList(_getDoctorList_inXML);
        System.out.println("getDoctorList.result=" + _getDoctorList__return);


        }
        {
        System.out.println("Invoking lisReWjz...");
        String _lisReWjz_inXML = "";
        String _lisReWjz__return = port.lisReWjz(_lisReWjz_inXML);
        System.out.println("lisReWjz.result=" + _lisReWjz__return);


        }
        {
        System.out.println("Invoking reMzjcCTMRYysq...");
        String _reMzjcCTMRYysq_inXML = "";
        String _reMzjcCTMRYysq__return = port.reMzjcCTMRYysq(_reMzjcCTMRYysq_inXML);
        System.out.println("reMzjcCTMRYysq.result=" + _reMzjcCTMRYysq__return);


        }
        {
        System.out.println("Invoking getITFOtType...");
        String _getITFOtType__return = port.getITFOtType();
        System.out.println("getITFOtType.result=" + _getITFOtType__return);


        }
        {
        System.out.println("Invoking getZyjcYysq...");
        String _getZyjcYysq_inXML = "";
        String _getZyjcYysq__return = port.getZyjcYysq(_getZyjcYysq_inXML);
        System.out.println("getZyjcYysq.result=" + _getZyjcYysq__return);


        }
        {
        System.out.println("Invoking getMzBrxxSfzh...");
        String _getMzBrxxSfzh_inXML = "";
        String _getMzBrxxSfzh__return = port.getMzBrxxSfzh(_getMzBrxxSfzh_inXML);
        System.out.println("getMzBrxxSfzh.result=" + _getMzBrxxSfzh__return);


        }
        {
        System.out.println("Invoking getMzBrxxNy...");
        String _getMzBrxxNy_inXML = "";
        String _getMzBrxxNy__return = port.getMzBrxxNy(_getMzBrxxNy_inXML);
        System.out.println("getMzBrxxNy.result=" + _getMzBrxxNy__return);


        }
        {
        System.out.println("Invoking insertFymx...");
        String _insertFymx_inXML = "";
        String _insertFymx__return = port.insertFymx(_insertFymx_inXML);
        System.out.println("insertFymx.result=" + _insertFymx__return);


        }
        {
        System.out.println("Invoking getITFDrugMoveOp...");
        String _getITFDrugMoveOp_inXML = "";
        String _getITFDrugMoveOp__return = port.getITFDrugMoveOp(_getITFDrugMoveOp_inXML);
        System.out.println("getITFDrugMoveOp.result=" + _getITFDrugMoveOp__return);


        }
        {
        System.out.println("Invoking getMztgYydh...");
        String _getMztgYydh_inXML = "";
        String _getMztgYydh__return = port.getMztgYydh(_getMztgYydh_inXML);
        System.out.println("getMztgYydh.result=" + _getMztgYydh__return);


        }
        {
        System.out.println("Invoking getMzjcCTMRYyxx...");
        String _getMzjcCTMRYyxx_inXML = "";
        String _getMzjcCTMRYyxx__return = port.getMzjcCTMRYyxx(_getMzjcCTMRYyxx_inXML);
        System.out.println("getMzjcCTMRYyxx.result=" + _getMzjcCTMRYyxx__return);


        }
        {
        System.out.println("Invoking getITFDrugClassify...");
        String _getITFDrugClassify__return = port.getITFDrugClassify();
        System.out.println("getITFDrugClassify.result=" + _getITFDrugClassify__return);


        }
        {
        System.out.println("Invoking getLisCqshTmbhMz...");
        String _getLisCqshTmbhMz_inXML = "";
        String _getLisCqshTmbhMz__return = port.getLisCqshTmbhMz(_getLisCqshTmbhMz_inXML);
        System.out.println("getLisCqshTmbhMz.result=" + _getLisCqshTmbhMz__return);


        }
        {
        System.out.println("Invoking getKsysSdpbmx...");
        String _getKsysSdpbmx_inXML = "";
        String _getKsysSdpbmx__return = port.getKsysSdpbmx(_getKsysSdpbmx_inXML);
        System.out.println("getKsysSdpbmx.result=" + _getKsysSdpbmx__return);


        }
        {
        System.out.println("Invoking getJclx...");
        String _getJclx_inXML = "";
        String _getJclx__return = port.getJclx(_getJclx_inXML);
        System.out.println("getJclx.result=" + _getJclx__return);


        }
        {
        System.out.println("Invoking getyyxxbysqdxh...");
        String _getyyxxbysqdxh_inXML = "";
        String _getyyxxbysqdxh__return = port.getyyxxbysqdxh(_getyyxxbysqdxh_inXML);
        System.out.println("getyyxxbysqdxh.result=" + _getyyxxbysqdxh__return);


        }
        {
        System.out.println("Invoking getZySsyyxx...");
        String _getZySsyyxx_inXML = "";
        String _getZySsyyxx__return = port.getZySsyyxx(_getZySsyyxx_inXML);
        System.out.println("getZySsyyxx.result=" + _getZySsyyxx__return);


        }
        {
        System.out.println("Invoking createBrda...");
        String _createBrda_inXML = "";
        String _createBrda__return = port.createBrda(_createBrda_inXML);
        System.out.println("createBrda.result=" + _createBrda__return);


        }
        {
        System.out.println("Invoking pacsGetReportInfoMz...");
        String _pacsGetReportInfoMz_inXML = "";
        String _pacsGetReportInfoMz__return = port.pacsGetReportInfoMz(_pacsGetReportInfoMz_inXML);
        System.out.println("pacsGetReportInfoMz.result=" + _pacsGetReportInfoMz__return);


        }
        {
        System.out.println("Invoking cancelMzgh...");
        String _cancelMzgh_inXML = "";
        String _cancelMzgh__return = port.cancelMzgh(_cancelMzgh_inXML);
        System.out.println("cancelMzgh.result=" + _cancelMzgh__return);


        }
        {
        System.out.println("Invoking getSmtz...");
        int _getSmtz_code = 0;
        int _getSmtz__return = port.getSmtz(_getSmtz_code);
        System.out.println("getSmtz.result=" + _getSmtz__return);


        }
        {
        System.out.println("Invoking getKshy...");
        String _getKshy_inXML = "";
        String _getKshy__return = port.getKshy(_getKshy_inXML);
        System.out.println("getKshy.result=" + _getKshy__return);


        }
        {
        System.out.println("Invoking getChuFangListFphm...");
        String _getChuFangListFphm_inXML = "";
        String _getChuFangListFphm__return = port.getChuFangListFphm(_getChuFangListFphm_inXML);
        System.out.println("getChuFangListFphm.result=" + _getChuFangListFphm__return);


        }
        {
        System.out.println("Invoking updatePyxx...");
        String _updatePyxx_inXML = "";
        String _updatePyxx__return = port.updatePyxx(_updatePyxx_inXML);
        System.out.println("updatePyxx.result=" + _updatePyxx__return);


        }
        {
        System.out.println("Invoking getITFChargesOp...");
        String _getITFChargesOp_inXML = "";
        String _getITFChargesOp__return = port.getITFChargesOp(_getITFChargesOp_inXML);
        System.out.println("getITFChargesOp.result=" + _getITFChargesOp__return);


        }
        {
        System.out.println("Invoking getZyFymxKsdm...");
        String _getZyFymxKsdm_inXML = "";
        String _getZyFymxKsdm__return = port.getZyFymxKsdm(_getZyFymxKsdm_inXML);
        System.out.println("getZyFymxKsdm.result=" + _getZyFymxKsdm__return);


        }
        {
        System.out.println("Invoking getMzBrxxFlk...");
        String _getMzBrxxFlk_inXML = "";
        String _getMzBrxxFlk__return = port.getMzBrxxFlk(_getMzBrxxFlk_inXML);
        System.out.println("getMzBrxxFlk.result=" + _getMzBrxxFlk__return);


        }
        {
        System.out.println("Invoking getComboAndItemsInfo...");
        String _getComboAndItemsInfo_inXML = "";
        String _getComboAndItemsInfo__return = port.getComboAndItemsInfo(_getComboAndItemsInfo_inXML);
        System.out.println("getComboAndItemsInfo.result=" + _getComboAndItemsInfo__return);


        }
        {
        System.out.println("Invoking getITFSpec...");
        String _getITFSpec__return = port.getITFSpec();
        System.out.println("getITFSpec.result=" + _getITFSpec__return);


        }
        {
        System.out.println("Invoking getITFPatAdmissionOp...");
        String _getITFPatAdmissionOp_inXML = "";
        String _getITFPatAdmissionOp__return = port.getITFPatAdmissionOp(_getITFPatAdmissionOp_inXML);
        System.out.println("getITFPatAdmissionOp.result=" + _getITFPatAdmissionOp__return);


        }
        {
        System.out.println("Invoking getZyjsJsxm...");
        String _getZyjsJsxm_inXML = "";
        String _getZyjsJsxm__return = port.getZyjsJsxm(_getZyjsJsxm_inXML);
        System.out.println("getZyjsJsxm.result=" + _getZyjsJsxm__return);


        }
        {
        System.out.println("Invoking getSfxmList...");
        String _getSfxmList_inXML = "";
        String _getSfxmList__return = port.getSfxmList(_getSfxmList_inXML);
        System.out.println("getSfxmList.result=" + _getSfxmList__return);


        }
        {
        System.out.println("Invoking insertZybrYjjk...");
        String _insertZybrYjjk_inXML = "";
        String _insertZybrYjjk__return = port.insertZybrYjjk(_insertZybrYjjk_inXML);
        System.out.println("insertZybrYjjk.result=" + _insertZybrYjjk__return);


        }
        {
        System.out.println("Invoking getGyslyxxMx...");
        String _getGyslyxxMx_inXML = "";
        String _getGyslyxxMx__return = port.getGyslyxxMx(_getGyslyxxMx_inXML);
        System.out.println("getGyslyxxMx.result=" + _getGyslyxxMx__return);


        }
        {
        System.out.println("Invoking getZyBrxxCyrq...");
        String _getZyBrxxCyrq_inXML = "";
        String _getZyBrxxCyrq__return = port.getZyBrxxCyrq(_getZyBrxxCyrq_inXML);
        System.out.println("getZyBrxxCyrq.result=" + _getZyBrxxCyrq__return);


        }
        {
        System.out.println("Invoking getMustFeeItem...");
        String _getMustFeeItem_inXML = "";
        String _getMustFeeItem__return = port.getMustFeeItem(_getMustFeeItem_inXML);
        System.out.println("getMustFeeItem.result=" + _getMustFeeItem__return);


        }
        {
        System.out.println("Invoking getKstc...");
        String _getKstc_inXML = "";
        String _getKstc__return = port.getKstc(_getKstc_inXML);
        System.out.println("getKstc.result=" + _getKstc__return);


        }
        {
        System.out.println("Invoking getITFLisResultOp...");
        String _getITFLisResultOp_inXML = "";
        String _getITFLisResultOp__return = port.getITFLisResultOp(_getITFLisResultOp_inXML);
        System.out.println("getITFLisResultOp.result=" + _getITFLisResultOp__return);


        }
        {
        System.out.println("Invoking getLisInfoZy...");
        String _getLisInfoZy_inXML = "";
        String _getLisInfoZy__return = port.getLisInfoZy(_getLisInfoZy_inXML);
        System.out.println("getLisInfoZy.result=" + _getLisInfoZy__return);


        }
        {
        System.out.println("Invoking getMzjcCTMRSqdxxSqdxh...");
        String _getMzjcCTMRSqdxxSqdxh_inXML = "";
        String _getMzjcCTMRSqdxxSqdxh__return = port.getMzjcCTMRSqdxxSqdxh(_getMzjcCTMRSqdxxSqdxh_inXML);
        System.out.println("getMzjcCTMRSqdxxSqdxh.result=" + _getMzjcCTMRSqdxxSqdxh__return);


        }
        {
        System.out.println("Invoking getITFDrug...");
        String _getITFDrug__return = port.getITFDrug();
        System.out.println("getITFDrug.result=" + _getITFDrug__return);


        }
        {
        System.out.println("Invoking test...");
        String _test_mcardNo = "";
        String _test__return = port.test(_test_mcardNo);
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking getJyxmList...");
        String _getJyxmList_inXML = "";
        String _getJyxmList__return = port.getJyxmList(_getJyxmList_inXML);
        System.out.println("getJyxmList.result=" + _getJyxmList__return);


        }
        {
        System.out.println("Invoking reMzjySqdzt...");
        String _reMzjySqdzt_inXML = "";
        String _reMzjySqdzt__return = port.reMzjySqdzt(_reMzjySqdzt_inXML);
        System.out.println("reMzjySqdzt.result=" + _reMzjySqdzt__return);


        }
        {
        System.out.println("Invoking lisInsertWjz...");
        String _lisInsertWjz_inXML = "";
        String _lisInsertWjz__return = port.lisInsertWjz(_lisInsertWjz_inXML);
        System.out.println("lisInsertWjz.result=" + _lisInsertWjz__return);


        }
        {
        System.out.println("Invoking lisVHaisPathogen...");
        String _lisVHaisPathogen_inXML = "";
        String _lisVHaisPathogen__return = port.lisVHaisPathogen(_lisVHaisPathogen_inXML);
        System.out.println("lisVHaisPathogen.result=" + _lisVHaisPathogen__return);


        }
        {
        System.out.println("Invoking ackRefundMzReg...");
        String _ackRefundMzReg_inXML = "";
        String _ackRefundMzReg__return = port.ackRefundMzReg(_ackRefundMzReg_inXML);
        System.out.println("ackRefundMzReg.result=" + _ackRefundMzReg__return);


        }
        {
        System.out.println("Invoking getMzdmList...");
        String _getMzdmList_inXML = "";
        String _getMzdmList__return = port.getMzdmList(_getMzdmList_inXML);
        System.out.println("getMzdmList.result=" + _getMzdmList__return);


        }
        {
        System.out.println("Invoking getITFEmployeePostition...");
        String _getITFEmployeePostition__return = port.getITFEmployeePostition();
        System.out.println("getITFEmployeePostition.result=" + _getITFEmployeePostition__return);


        }
        {
        System.out.println("Invoking getYyxx...");
        String _getYyxx_inXML = "";
        String _getYyxx__return = port.getYyxx(_getYyxx_inXML);
        System.out.println("getYyxx.result=" + _getYyxx__return);


        }
        {
        System.out.println("Invoking getITFPatCharacterIp...");
        String _getITFPatCharacterIp_inXML = "";
        String _getITFPatCharacterIp__return = port.getITFPatCharacterIp(_getITFPatCharacterIp_inXML);
        System.out.println("getITFPatCharacterIp.result=" + _getITFPatCharacterIp__return);


        }
        {
        System.out.println("Invoking getDoctorType...");
        String _getDoctorType_inXML = "";
        String _getDoctorType__return = port.getDoctorType(_getDoctorType_inXML);
        System.out.println("getDoctorType.result=" + _getDoctorType__return);


        }
        {
        System.out.println("Invoking blGetReportInfo...");
        String _blGetReportInfo_inXML = "";
        String _blGetReportInfo__return = port.blGetReportInfo(_blGetReportInfo_inXML);
        System.out.println("blGetReportInfo.result=" + _blGetReportInfo__return);


        }
        {
        System.out.println("Invoking getITFAllergyIp...");
        String _getITFAllergyIp_inXML = "";
        String _getITFAllergyIp__return = port.getITFAllergyIp(_getITFAllergyIp_inXML);
        System.out.println("getITFAllergyIp.result=" + _getITFAllergyIp__return);


        }
        {
        System.out.println("Invoking insertSmtz...");
        String _insertSmtz_inXML = "";
        String _insertSmtz__return = port.insertSmtz(_insertSmtz_inXML);
        System.out.println("insertSmtz.result=" + _insertSmtz__return);


        }
        {
        System.out.println("Invoking cancelMzjcYysq...");
        String _cancelMzjcYysq_inXML = "";
        String _cancelMzjcYysq__return = port.cancelMzjcYysq(_cancelMzjcYysq_inXML);
        System.out.println("cancelMzjcYysq.result=" + _cancelMzjcYysq__return);


        }
        {
        System.out.println("Invoking cancelYyxx...");
        String _cancelYyxx_inXML = "";
        String _cancelYyxx__return = port.cancelYyxx(_cancelYyxx_inXML);
        System.out.println("cancelYyxx.result=" + _cancelYyxx__return);


        }
        {
        System.out.println("Invoking lisVHaisAntiName...");
        String _lisVHaisAntiName_inXML = "";
        String _lisVHaisAntiName__return = port.lisVHaisAntiName(_lisVHaisAntiName_inXML);
        System.out.println("lisVHaisAntiName.result=" + _lisVHaisAntiName__return);


        }
        {
        System.out.println("Invoking getZybrJsxx...");
        String _getZybrJsxx_inXML = "";
        String _getZybrJsxx__return = port.getZybrJsxx(_getZybrJsxx_inXML);
        System.out.println("getZybrJsxx.result=" + _getZybrJsxx__return);


        }
        {
        System.out.println("Invoking reMzjcYysq...");
        String _reMzjcYysq_inXML = "";
        String _reMzjcYysq__return = port.reMzjcYysq(_reMzjcYysq_inXML);
        System.out.println("reMzjcYysq.result=" + _reMzjcYysq__return);


        }
        {
        System.out.println("Invoking getYshy...");
        String _getYshy_inXML = "";
        String _getYshy__return = port.getYshy(_getYshy_inXML);
        System.out.println("getYshy.result=" + _getYshy__return);


        }
        {
        System.out.println("Invoking getMzBrxxFphm...");
        String _getMzBrxxFphm_inXML = "";
        String _getMzBrxxFphm__return = port.getMzBrxxFphm(_getMzBrxxFphm_inXML);
        System.out.println("getMzBrxxFphm.result=" + _getMzBrxxFphm__return);


        }
        {
        System.out.println("Invoking getZyFymxTmbh...");
        String _getZyFymxTmbh_inXML = "";
        String _getZyFymxTmbh__return = port.getZyFymxTmbh(_getZyFymxTmbh_inXML);
        System.out.println("getZyFymxTmbh.result=" + _getZyFymxTmbh__return);


        }
        {
        System.out.println("Invoking ecgGetReportInfoMz...");
        String _ecgGetReportInfoMz_inXML = "";
        String _ecgGetReportInfoMz__return = port.ecgGetReportInfoMz(_ecgGetReportInfoMz_inXML);
        System.out.println("ecgGetReportInfoMz.result=" + _ecgGetReportInfoMz__return);


        }
        {
        System.out.println("Invoking insertCffyzs...");
        String _insertCffyzs_inXML = "";
        String _insertCffyzs__return = port.insertCffyzs(_insertCffyzs_inXML);
        System.out.println("insertCffyzs.result=" + _insertCffyzs__return);


        }
        {
        System.out.println("Invoking getHospitalId...");
        String _getHospitalId__return = port.getHospitalId();
        System.out.println("getHospitalId.result=" + _getHospitalId__return);


        }
        {
        System.out.println("Invoking reZyjcYysq...");
        String _reZyjcYysq_inXML = "";
        String _reZyjcYysq__return = port.reZyjcYysq(_reZyjcYysq_inXML);
        System.out.println("reZyjcYysq.result=" + _reZyjcYysq__return);


        }
        {
        System.out.println("Invoking lisGetReportInfo...");
        String _lisGetReportInfo_inXML = "";
        String _lisGetReportInfo__return = port.lisGetReportInfo(_lisGetReportInfo_inXML);
        System.out.println("lisGetReportInfo.result=" + _lisGetReportInfo__return);


        }
        {
        System.out.println("Invoking getITFRcptPolicy...");
        String _getITFRcptPolicy__return = port.getITFRcptPolicy();
        System.out.println("getITFRcptPolicy.result=" + _getITFRcptPolicy__return);


        }
        {
        System.out.println("Invoking getZyBrxxRycs...");
        String _getZyBrxxRycs_inXML = "";
        String _getZyBrxxRycs__return = port.getZyBrxxRycs(_getZyBrxxRycs_inXML);
        System.out.println("getZyBrxxRycs.result=" + _getZyBrxxRycs__return);


        }
        {
        System.out.println("Invoking getDzxx...");
        String _getDzxx_inXML = "";
        String _getDzxx__return = port.getDzxx(_getDzxx_inXML);
        System.out.println("getDzxx.result=" + _getDzxx__return);


        }
        {
        System.out.println("Invoking getChuFangListMzhmRq...");
        String _getChuFangListMzhmRq_inXML = "";
        String _getChuFangListMzhmRq__return = port.getChuFangListMzhmRq(_getChuFangListMzhmRq_inXML);
        System.out.println("getChuFangListMzhmRq.result=" + _getChuFangListMzhmRq__return);


        }
        {
        System.out.println("Invoking getGhks...");
        String _getGhks_inXML = "";
        String _getGhks__return = port.getGhks(_getGhks_inXML);
        System.out.println("getGhks.result=" + _getGhks__return);


        }
        {
        System.out.println("Invoking getITFEmployee...");
        String _getITFEmployee__return = port.getITFEmployee();
        System.out.println("getITFEmployee.result=" + _getITFEmployee__return);


        }
        {
        System.out.println("Invoking getSdpb...");
        String _getSdpb_inXML = "";
        String _getSdpb__return = port.getSdpb(_getSdpb_inXML);
        System.out.println("getSdpb.result=" + _getSdpb__return);


        }
        {
        System.out.println("Invoking getZyBlnrCyrq...");
        String _getZyBlnrCyrq_inXML = "";
        String _getZyBlnrCyrq__return = port.getZyBlnrCyrq(_getZyBlnrCyrq_inXML);
        System.out.println("getZyBlnrCyrq.result=" + _getZyBlnrCyrq__return);


        }
        {
        System.out.println("Invoking mzChuFangZf...");
        String _mzChuFangZf_inXML = "";
        String _mzChuFangZf__return = port.mzChuFangZf(_mzChuFangZf_inXML);
        System.out.println("mzChuFangZf.result=" + _mzChuFangZf__return);


        }
        {
        System.out.println("Invoking createMzgh...");
        String _createMzgh_inXML = "";
        String _createMzgh__return = port.createMzgh(_createMzgh_inXML);
        System.out.println("createMzgh.result=" + _createMzgh__return);


        }
        {
        System.out.println("Invoking getCriticalValueMedicalTech...");
        String _getCriticalValueMedicalTech_inXML = "";
        String _getCriticalValueMedicalTech__return = port.getCriticalValueMedicalTech(_getCriticalValueMedicalTech_inXML);
        System.out.println("getCriticalValueMedicalTech.result=" + _getCriticalValueMedicalTech__return);


        }
        {
        System.out.println("Invoking caCreateKey...");
        String _caCreateKey__return = port.caCreateKey();
        System.out.println("caCreateKey.result=" + _caCreateKey__return);


        }
        {
        System.out.println("Invoking getChuFangMxNy...");
        String _getChuFangMxNy_inXML = "";
        String _getChuFangMxNy__return = port.getChuFangMxNy(_getChuFangMxNy_inXML);
        System.out.println("getChuFangMxNy.result=" + _getChuFangMxNy__return);


        }
        {
        System.out.println("Invoking getZySsbr...");
        String _getZySsbr_inXML = "";
        String _getZySsbr__return = port.getZySsbr(_getZySsbr_inXML);
        System.out.println("getZySsbr.result=" + _getZySsbr__return);


        }
        {
        System.out.println("Invoking getZyXmsfmx...");
        String _getZyXmsfmx_inXML = "";
        String _getZyXmsfmx__return = port.getZyXmsfmx(_getZyXmsfmx_inXML);
        System.out.println("getZyXmsfmx.result=" + _getZyXmsfmx__return);


        }
        {
        System.out.println("Invoking createBrdaMzgh...");
        String _createBrdaMzgh_inXML = "";
        String _createBrdaMzgh__return = port.createBrdaMzgh(_createBrdaMzgh_inXML);
        System.out.println("createBrdaMzgh.result=" + _createBrdaMzgh__return);


        }
        {
        System.out.println("Invoking getCwbbList...");
        String _getCwbbList_inXML = "";
        String _getCwbbList__return = port.getCwbbList(_getCwbbList_inXML);
        System.out.println("getCwbbList.result=" + _getCwbbList__return);


        }
        {
        System.out.println("Invoking getZybrZkjl...");
        String _getZybrZkjl_inXML = "";
        String _getZybrZkjl__return = port.getZybrZkjl(_getZybrZkjl_inXML);
        System.out.println("getZybrZkjl.result=" + _getZybrZkjl__return);


        }
        {
        System.out.println("Invoking getZyBrxxCx...");
        String _getZyBrxxCx_inXML = "";
        String _getZyBrxxCx__return = port.getZyBrxxCx(_getZyBrxxCx_inXML);
        System.out.println("getZyBrxxCx.result=" + _getZyBrxxCx__return);


        }
        {
        System.out.println("Invoking xkGetBarcode...");
        String _xkGetBarcode_inXML = "";
        String _xkGetBarcode__return = port.xkGetBarcode(_xkGetBarcode_inXML);
        System.out.println("xkGetBarcode.result=" + _xkGetBarcode__return);


        }
        {
        System.out.println("Invoking getZyBrxxBrwd...");
        String _getZyBrxxBrwd_inXML = "";
        String _getZyBrxxBrwd__return = port.getZyBrxxBrwd(_getZyBrxxBrwd_inXML);
        System.out.println("getZyBrxxBrwd.result=" + _getZyBrxxBrwd__return);


        }
        {
        System.out.println("Invoking getZybrSmtzByZyhm...");
        String _getZybrSmtzByZyhm_inXML = "";
        String _getZybrSmtzByZyhm__return = port.getZybrSmtzByZyhm(_getZybrSmtzByZyhm_inXML);
        System.out.println("getZybrSmtzByZyhm.result=" + _getZybrSmtzByZyhm__return);


        }
        {
        System.out.println("Invoking getGysWpxxList...");
        String _getGysWpxxList_inXML = "";
        String _getGysWpxxList__return = port.getGysWpxxList(_getGysWpxxList_inXML);
        System.out.println("getGysWpxxList.result=" + _getGysWpxxList__return);


        }
        {
        System.out.println("Invoking getMzjcCTMRYysj...");
        String _getMzjcCTMRYysj_inXML = "";
        String _getMzjcCTMRYysj__return = port.getMzjcCTMRYysj(_getMzjcCTMRYysj_inXML);
        System.out.println("getMzjcCTMRYysj.result=" + _getMzjcCTMRYysj__return);


        }
        {
        System.out.println("Invoking szCaLognCheck...");
        String _szCaLognCheck_inXML = "";
        String _szCaLognCheck__return = port.szCaLognCheck(_szCaLognCheck_inXML);
        System.out.println("szCaLognCheck.result=" + _szCaLognCheck__return);


        }
        {
        System.out.println("Invoking getKspb...");
        String _getKspb_inXML = "";
        String _getKspb__return = port.getKspb(_getKspb_inXML);
        System.out.println("getKspb.result=" + _getKspb__return);


        }
        {
        System.out.println("Invoking logIn...");
        String _logIn_logid = "";
        String _logIn_password = "";
        String _logIn__return = port.logIn(_logIn_logid, _logIn_password);
        System.out.println("logIn.result=" + _logIn__return);


        }
        {
        System.out.println("Invoking ybSaveMZGH...");
        String _ybSaveMZGH_inXML = "";
        String _ybSaveMZGH__return = port.ybSaveMZGH(_ybSaveMZGH_inXML);
        System.out.println("ybSaveMZGH.result=" + _ybSaveMZGH__return);


        }
        {
        System.out.println("Invoking getMzJzxx...");
        String _getMzJzxx_inXML = "";
        String _getMzJzxx__return = port.getMzJzxx(_getMzJzxx_inXML);
        System.out.println("getMzJzxx.result=" + _getMzJzxx__return);


        }
        {
        System.out.println("Invoking getChuFangListDnhRq...");
        String _getChuFangListDnhRq_inXML = "";
        String _getChuFangListDnhRq__return = port.getChuFangListDnhRq(_getChuFangListDnhRq_inXML);
        System.out.println("getChuFangListDnhRq.result=" + _getChuFangListDnhRq__return);


        }
        {
        System.out.println("Invoking getZySyxx...");
        String _getZySyxx_inXML = "";
        String _getZySyxx__return = port.getZySyxx(_getZySyxx_inXML);
        System.out.println("getZySyxx.result=" + _getZySyxx__return);


        }
        {
        System.out.println("Invoking getZyBrxxCyrqWithoutJs...");
        String _getZyBrxxCyrqWithoutJs_inXML = "";
        String _getZyBrxxCyrqWithoutJs__return = port.getZyBrxxCyrqWithoutJs(_getZyBrxxCyrqWithoutJs_inXML);
        System.out.println("getZyBrxxCyrqWithoutJs.result=" + _getZyBrxxCyrqWithoutJs__return);


        }
        {
        System.out.println("Invoking createBank...");
        String _createBank_inXML = "";
        String _createBank__return = port.createBank(_createBank_inXML);
        System.out.println("createBank.result=" + _createBank__return);


        }
        {
        System.out.println("Invoking getBrxz...");
        String _getBrxz_inXML = "";
        String _getBrxz__return = port.getBrxz(_getBrxz_inXML);
        System.out.println("getBrxz.result=" + _getBrxz__return);


        }
        {
        System.out.println("Invoking getITFDrugMoveIp...");
        String _getITFDrugMoveIp_inXML = "";
        String _getITFDrugMoveIp__return = port.getITFDrugMoveIp(_getITFDrugMoveIp_inXML);
        System.out.println("getITFDrugMoveIp.result=" + _getITFDrugMoveIp__return);


        }
        {
        System.out.println("Invoking getITFWardSpec...");
        String _getITFWardSpec__return = port.getITFWardSpec();
        System.out.println("getITFWardSpec.result=" + _getITFWardSpec__return);


        }
        {
        System.out.println("Invoking getITFPatPatinfoIp...");
        String _getITFPatPatinfoIp_inXML = "";
        String _getITFPatPatinfoIp__return = port.getITFPatPatinfoIp(_getITFPatPatinfoIp_inXML);
        System.out.println("getITFPatPatinfoIp.result=" + _getITFPatPatinfoIp__return);


        }
        {
        System.out.println("Invoking reMzjcSqzx...");
        String _reMzjcSqzx_inXML = "";
        String _reMzjcSqzx__return = port.reMzjcSqzx(_reMzjcSqzx_inXML);
        System.out.println("reMzjcSqzx.result=" + _reMzjcSqzx__return);


        }
        {
        System.out.println("Invoking createYyxx...");
        String _createYyxx_inXML = "";
        String _createYyxx__return = port.createYyxx(_createYyxx_inXML);
        System.out.println("createYyxx.result=" + _createYyxx__return);


        }
        {
        System.out.println("Invoking getZybrSmtz...");
        String _getZybrSmtz_inXML = "";
        String _getZybrSmtz__return = port.getZybrSmtz(_getZybrSmtz_inXML);
        System.out.println("getZybrSmtz.result=" + _getZybrSmtz__return);


        }
        {
        System.out.println("Invoking getZyjsYbzfxm...");
        String _getZyjsYbzfxm_inXML = "";
        String _getZyjsYbzfxm__return = port.getZyjsYbzfxm(_getZyjsYbzfxm_inXML);
        System.out.println("getZyjsYbzfxm.result=" + _getZyjsYbzfxm__return);


        }
        {
        System.out.println("Invoking getyyxxbyksdm...");
        String _getyyxxbyksdm_inXML = "";
        String _getyyxxbyksdm__return = port.getyyxxbyksdm(_getyyxxbyksdm_inXML);
        System.out.println("getyyxxbyksdm.result=" + _getyyxxbyksdm__return);


        }
        {
        System.out.println("Invoking getChuFangListKdksRq...");
        String _getChuFangListKdksRq_inXML = "";
        String _getChuFangListKdksRq__return = port.getChuFangListKdksRq(_getChuFangListKdksRq_inXML);
        System.out.println("getChuFangListKdksRq.result=" + _getChuFangListKdksRq__return);


        }
        {
        System.out.println("Invoking getZybrxxDbz...");
        String _getZybrxxDbz_inXML = "";
        String _getZybrxxDbz__return = port.getZybrxxDbz(_getZybrxxDbz_inXML);
        System.out.println("getZybrxxDbz.result=" + _getZybrxxDbz__return);


        }
        {
        System.out.println("Invoking getCriticalValuesInfoPatientInfo...");
        String _getCriticalValuesInfoPatientInfo_inXML = "";
        String _getCriticalValuesInfoPatientInfo__return = port.getCriticalValuesInfoPatientInfo(_getCriticalValuesInfoPatientInfo_inXML);
        System.out.println("getCriticalValuesInfoPatientInfo.result=" + _getCriticalValuesInfoPatientInfo__return);


        }
        {
        System.out.println("Invoking szCaValidSign...");
        String _szCaValidSign_asPubkey = "";
        String _szCaValidSign_asQmjg = "";
        String _szCaValidSign_asQmyw = "";
        String _szCaValidSign_inXML = "";
        String _szCaValidSign__return = port.szCaValidSign(_szCaValidSign_asPubkey, _szCaValidSign_asQmjg, _szCaValidSign_asQmyw, _szCaValidSign_inXML);
        System.out.println("szCaValidSign.result=" + _szCaValidSign__return);


        }
        {
        System.out.println("Invoking getDepartment...");
        String _getDepartment_inXML = "";
        String _getDepartment__return = port.getDepartment(_getDepartment_inXML);
        System.out.println("getDepartment.result=" + _getDepartment__return);


        }
        {
        System.out.println("Invoking getLisListKsdmZy...");
        String _getLisListKsdmZy_inXML = "";
        String _getLisListKsdmZy__return = port.getLisListKsdmZy(_getLisListKsdmZy_inXML);
        System.out.println("getLisListKsdmZy.result=" + _getLisListKsdmZy__return);


        }
        {
        System.out.println("Invoking ecgGetReportInfo...");
        String _ecgGetReportInfo_inXML = "";
        String _ecgGetReportInfo__return = port.ecgGetReportInfo(_ecgGetReportInfo_inXML);
        System.out.println("ecgGetReportInfo.result=" + _ecgGetReportInfo__return);


        }
        {
        System.out.println("Invoking getBqhy...");
        String _getBqhy_inXML = "";
        String _getBqhy__return = port.getBqhy(_getBqhy_inXML);
        System.out.println("getBqhy.result=" + _getBqhy__return);


        }
        {
        System.out.println("Invoking getZyjsFymx...");
        String _getZyjsFymx_inXML = "";
        String _getZyjsFymx__return = port.getZyjsFymx(_getZyjsFymx_inXML);
        System.out.println("getZyjsFymx.result=" + _getZyjsFymx__return);


        }
        {
        System.out.println("Invoking getGhxx...");
        String _getGhxx_inXML = "";
        String _getGhxx__return = port.getGhxx(_getGhxx_inXML);
        System.out.println("getGhxx.result=" + _getGhxx__return);


        }
        {
        System.out.println("Invoking getITFDrugRightLimit...");
        String _getITFDrugRightLimit__return = port.getITFDrugRightLimit();
        System.out.println("getITFDrugRightLimit.result=" + _getITFDrugRightLimit__return);


        }
        {
        System.out.println("Invoking getITFDrugClassifyRelation...");
        String _getITFDrugClassifyRelation__return = port.getITFDrugClassifyRelation();
        System.out.println("getITFDrugClassifyRelation.result=" + _getITFDrugClassifyRelation__return);


        }
        {
        System.out.println("Invoking getSigndataJcxxMz...");
        String _getSigndataJcxxMz_inXML = "";
        String _getSigndataJcxxMz__return = port.getSigndataJcxxMz(_getSigndataJcxxMz_inXML);
        System.out.println("getSigndataJcxxMz.result=" + _getSigndataJcxxMz__return);


        }
        {
        System.out.println("Invoking getITFPrescribeIp...");
        String _getITFPrescribeIp_inXML = "";
        String _getITFPrescribeIp__return = port.getITFPrescribeIp(_getITFPrescribeIp_inXML);
        System.out.println("getITFPrescribeIp.result=" + _getITFPrescribeIp__return);


        }
        {
        System.out.println("Invoking getLisListMzhm...");
        String _getLisListMzhm_inXML = "";
        String _getLisListMzhm__return = port.getLisListMzhm(_getLisListMzhm_inXML);
        System.out.println("getLisListMzhm.result=" + _getLisListMzhm__return);


        }
        {
        System.out.println("Invoking getITFPatDiagnosisOp...");
        String _getITFPatDiagnosisOp_inXML = "";
        String _getITFPatDiagnosisOp__return = port.getITFPatDiagnosisOp(_getITFPatDiagnosisOp_inXML);
        System.out.println("getITFPatDiagnosisOp.result=" + _getITFPatDiagnosisOp__return);


        }
        {
        System.out.println("Invoking getZyBlList...");
        String _getZyBlList_inXML = "";
        String _getZyBlList__return = port.getZyBlList(_getZyBlList_inXML);
        System.out.println("getZyBlList.result=" + _getZyBlList__return);


        }
        {
        System.out.println("Invoking getHisdatetime...");
        javax.xml.datatype.XMLGregorianCalendar _getHisdatetime__return = port.getHisdatetime();
        System.out.println("getHisdatetime.result=" + _getHisdatetime__return);


        }
        {
        System.out.println("Invoking getZybrxxDbzlb...");
        String _getZybrxxDbzlb_inXML = "";
        String _getZybrxxDbzlb__return = port.getZybrxxDbzlb(_getZybrxxDbzlb_inXML);
        System.out.println("getZybrxxDbzlb.result=" + _getZybrxxDbzlb__return);


        }
        {
        System.out.println("Invoking getYsdlks...");
        String _getYsdlks_inXML = "";
        String _getYsdlks__return = port.getYsdlks(_getYsdlks_inXML);
        System.out.println("getYsdlks.result=" + _getYsdlks__return);


        }
        {
        System.out.println("Invoking cancelMzChuFangZf...");
        String _cancelMzChuFangZf_inXML = "";
        String _cancelMzChuFangZf__return = port.cancelMzChuFangZf(_cancelMzChuFangZf_inXML);
        System.out.println("cancelMzChuFangZf.result=" + _cancelMzChuFangZf__return);


        }
        {
        System.out.println("Invoking insertSsap...");
        String _insertSsap_inXML = "";
        String _insertSsap__return = port.insertSsap(_insertSsap_inXML);
        System.out.println("insertSsap.result=" + _insertSsap__return);


        }
        {
        System.out.println("Invoking pacsGetReportInfo...");
        String _pacsGetReportInfo_inXML = "";
        String _pacsGetReportInfo__return = port.pacsGetReportInfo(_pacsGetReportInfo_inXML);
        System.out.println("pacsGetReportInfo.result=" + _pacsGetReportInfo__return);


        }
        {
        System.out.println("Invoking getZyBrxxHsrq...");
        String _getZyBrxxHsrq_inXML = "";
        String _getZyBrxxHsrq__return = port.getZyBrxxHsrq(_getZyBrxxHsrq_inXML);
        System.out.println("getZyBrxxHsrq.result=" + _getZyBrxxHsrq__return);


        }
        {
        System.out.println("Invoking mzybFysc...");
        String _mzybFysc_inXML = "";
        String _mzybFysc__return = port.mzybFysc(_mzybFysc_inXML);
        System.out.println("mzybFysc.result=" + _mzybFysc__return);


        }
        {
        System.out.println("Invoking getYbdm...");
        String _getYbdm_inXML = "";
        String _getYbdm__return = port.getYbdm(_getYbdm_inXML);
        System.out.println("getYbdm.result=" + _getYbdm__return);


        }
        {
        System.out.println("Invoking getChuFangListSfzhRq...");
        String _getChuFangListSfzhRq_inXML = "";
        String _getChuFangListSfzhRq__return = port.getChuFangListSfzhRq(_getChuFangListSfzhRq_inXML);
        System.out.println("getChuFangListSfzhRq.result=" + _getChuFangListSfzhRq__return);


        }
        {
        System.out.println("Invoking ybRefundMZGH...");
        String _ybRefundMZGH_inXML = "";
        String _ybRefundMZGH__return = port.ybRefundMZGH(_ybRefundMZGH_inXML);
        System.out.println("ybRefundMZGH.result=" + _ybRefundMZGH__return);


        }
        {
        System.out.println("Invoking getLisInfoMz...");
        String _getLisInfoMz_inXML = "";
        String _getLisInfoMz__return = port.getLisInfoMz(_getLisInfoMz_inXML);
        System.out.println("getLisInfoMz.result=" + _getLisInfoMz__return);


        }
        {
        System.out.println("Invoking getZybrZyzd...");
        String _getZybrZyzd_inXML = "";
        String _getZybrZyzd__return = port.getZybrZyzd(_getZybrZyzd_inXML);
        System.out.println("getZybrZyzd.result=" + _getZybrZyzd__return);


        }
        {
        System.out.println("Invoking cancelCTMRYysq...");
        String _cancelCTMRYysq_inXML = "";
        String _cancelCTMRYysq__return = port.cancelCTMRYysq(_cancelCTMRYysq_inXML);
        System.out.println("cancelCTMRYysq.result=" + _cancelCTMRYysq__return);


        }
        {
        System.out.println("Invoking caVerifySignedHash...");
        String _caVerifySignedHash_inXML = "";
        String _caVerifySignedHash__return = port.caVerifySignedHash(_caVerifySignedHash_inXML);
        System.out.println("caVerifySignedHash.result=" + _caVerifySignedHash__return);


        }
        {
        System.out.println("Invoking getZyBrxx...");
        String _getZyBrxx_inXML = "";
        String _getZyBrxx__return = port.getZyBrxx(_getZyBrxx_inXML);
        System.out.println("getZyBrxx.result=" + _getZyBrxx__return);


        }
        {
        System.out.println("Invoking setCwbbWcbz...");
        String _setCwbbWcbz_inXML = "";
        String _setCwbbWcbz__return = port.setCwbbWcbz(_setCwbbWcbz_inXML);
        System.out.println("setCwbbWcbz.result=" + _setCwbbWcbz__return);


        }
        {
        System.out.println("Invoking getZyYrfyqd...");
        String _getZyYrfyqd_inXML = "";
        String _getZyYrfyqd__return = port.getZyYrfyqd(_getZyYrfyqd_inXML);
        System.out.println("getZyYrfyqd.result=" + _getZyYrfyqd__return);


        }
        {
        System.out.println("Invoking setMySoapHeader...");
        String _setMySoapHeader_userName = "";
        String _setMySoapHeader_passWord = "";
        String _setMySoapHeader_yyid = "";
        String _setMySoapHeader__return = port.setMySoapHeader(_setMySoapHeader_userName, _setMySoapHeader_passWord, _setMySoapHeader_yyid);
        System.out.println("setMySoapHeader.result=" + _setMySoapHeader__return);


        }
        {
        System.out.println("Invoking getChuFangListCfsb...");
        String _getChuFangListCfsb_inXML = "";
        String _getChuFangListCfsb__return = port.getChuFangListCfsb(_getChuFangListCfsb_inXML);
        System.out.println("getChuFangListCfsb.result=" + _getChuFangListCfsb__return);


        }
        {
        System.out.println("Invoking getITFAdminRoute...");
        String _getITFAdminRoute__return = port.getITFAdminRoute();
        System.out.println("getITFAdminRoute.result=" + _getITFAdminRoute__return);


        }
        {
        System.out.println("Invoking ybRefundMZInsurance...");
        String _ybRefundMZInsurance_inXML = "";
        String _ybRefundMZInsurance__return = port.ybRefundMZInsurance(_ybRefundMZInsurance_inXML);
        System.out.println("ybRefundMZInsurance.result=" + _ybRefundMZInsurance__return);


        }
        {
        System.out.println("Invoking getZySsxx...");
        String _getZySsxx_inXML = "";
        String _getZySsxx__return = port.getZySsxx(_getZySsxx_inXML);
        System.out.println("getZySsxx.result=" + _getZySsxx__return);


        }
        {
        System.out.println("Invoking getITFDiagnosisIp...");
        String _getITFDiagnosisIp_inXML = "";
        String _getITFDiagnosisIp__return = port.getITFDiagnosisIp(_getITFDiagnosisIp_inXML);
        System.out.println("getITFDiagnosisIp.result=" + _getITFDiagnosisIp__return);


        }
        {
        System.out.println("Invoking getZyBrxxKsdmFlk...");
        String _getZyBrxxKsdmFlk_inXML = "";
        String _getZyBrxxKsdmFlk__return = port.getZyBrxxKsdmFlk(_getZyBrxxKsdmFlk_inXML);
        System.out.println("getZyBrxxKsdmFlk.result=" + _getZyBrxxKsdmFlk__return);


        }
        {
        System.out.println("Invoking ackRefundReg...");
        String _ackRefundReg_inXML = "";
        String _ackRefundReg__return = port.ackRefundReg(_ackRefundReg_inXML);
        System.out.println("ackRefundReg.result=" + _ackRefundReg__return);


        }
        {
        System.out.println("Invoking getITFDiagnosis...");
        String _getITFDiagnosis__return = port.getITFDiagnosis();
        System.out.println("getITFDiagnosis.result=" + _getITFDiagnosis__return);


        }
        {
        System.out.println("Invoking getPacsInfoMz...");
        String _getPacsInfoMz_inXML = "";
        String _getPacsInfoMz__return = port.getPacsInfoMz(_getPacsInfoMz_inXML);
        System.out.println("getPacsInfoMz.result=" + _getPacsInfoMz__return);


        }
        {
        System.out.println("Invoking ybSettleMZInsurance...");
        String _ybSettleMZInsurance_inXML = "";
        String _ybSettleMZInsurance__return = port.ybSettleMZInsurance(_ybSettleMZInsurance_inXML);
        System.out.println("ybSettleMZInsurance.result=" + _ybSettleMZInsurance__return);


        }
        {
        System.out.println("Invoking caHashAndSign...");
        String _caHashAndSign_inXML = "";
        String _caHashAndSign__return = port.caHashAndSign(_caHashAndSign_inXML);
        System.out.println("caHashAndSign.result=" + _caHashAndSign__return);


        }
        {
        System.out.println("Invoking getUserId...");
        String _getUserId__return = port.getUserId();
        System.out.println("getUserId.result=" + _getUserId__return);


        }
        {
        System.out.println("Invoking getLisListTmbhMz...");
        String _getLisListTmbhMz_inXML = "";
        String _getLisListTmbhMz__return = port.getLisListTmbhMz(_getLisListTmbhMz_inXML);
        System.out.println("getLisListTmbhMz.result=" + _getLisListTmbhMz__return);


        }
        {
        System.out.println("Invoking getITFChargesIp...");
        String _getITFChargesIp_inXML = "";
        String _getITFChargesIp__return = port.getITFChargesIp(_getITFChargesIp_inXML);
        System.out.println("getITFChargesIp.result=" + _getITFChargesIp__return);


        }
        {
        System.out.println("Invoking getLisListZyhm...");
        String _getLisListZyhm_inXML = "";
        String _getLisListZyhm__return = port.getLisListZyhm(_getLisListZyhm_inXML);
        System.out.println("getLisListZyhm.result=" + _getLisListZyhm__return);


        }
        {
        System.out.println("Invoking getComboForItemList...");
        String _getComboForItemList_inXML = "";
        String _getComboForItemList__return = port.getComboForItemList(_getComboForItemList_inXML);
        System.out.println("getComboForItemList.result=" + _getComboForItemList__return);


        }
        {
        System.out.println("Invoking getMzjcCTMRSqdxx...");
        String _getMzjcCTMRSqdxx_inXML = "";
        String _getMzjcCTMRSqdxx__return = port.getMzjcCTMRSqdxx(_getMzjcCTMRSqdxx_inXML);
        System.out.println("getMzjcCTMRSqdxx.result=" + _getMzjcCTMRSqdxx__return);


        }
        {
        System.out.println("Invoking getZySqssmc...");
        String _getZySqssmc_inXML = "";
        String _getZySqssmc__return = port.getZySqssmc(_getZySqssmc_inXML);
        System.out.println("getZySqssmc.result=" + _getZySqssmc__return);


        }
        {
        System.out.println("Invoking cancelMzyfLed...");
        String _cancelMzyfLed_inXML = "";
        String _cancelMzyfLed__return = port.cancelMzyfLed(_cancelMzyfLed_inXML);
        System.out.println("cancelMzyfLed.result=" + _cancelMzyfLed__return);


        }
        {
        System.out.println("Invoking reKtf...");
        String _reKtf_inXML = "";
        String _reKtf__return = port.reKtf(_reKtf_inXML);
        System.out.println("reKtf.result=" + _reKtf__return);


        }
        {
        System.out.println("Invoking getITFWard...");
        String _getITFWard__return = port.getITFWard();
        System.out.println("getITFWard.result=" + _getITFWard__return);


        }
        {
        System.out.println("Invoking bcGetReportInfo...");
        String _bcGetReportInfo_inXML = "";
        String _bcGetReportInfo__return = port.bcGetReportInfo(_bcGetReportInfo_inXML);
        System.out.println("bcGetReportInfo.result=" + _bcGetReportInfo__return);


        }
        {
        System.out.println("Invoking getITFPrescribeType...");
        String _getITFPrescribeType__return = port.getITFPrescribeType();
        System.out.println("getITFPrescribeType.result=" + _getITFPrescribeType__return);


        }
        {
        System.out.println("Invoking getMzBrxxSqdxh...");
        String _getMzBrxxSqdxh_inXML = "";
        String _getMzBrxxSqdxh__return = port.getMzBrxxSqdxh(_getMzBrxxSqdxh_inXML);
        System.out.println("getMzBrxxSqdxh.result=" + _getMzBrxxSqdxh__return);


        }
        {
        System.out.println("Invoking insertSsfy...");
        String _insertSsfy_inXML = "";
        String _insertSsfy__return = port.insertSsfy(_insertSsfy_inXML);
        System.out.println("insertSsfy.result=" + _insertSsfy__return);


        }
        {
        System.out.println("Invoking getBasysjSsxx...");
        String _getBasysjSsxx_inXML = "";
        String _getBasysjSsxx__return = port.getBasysjSsxx(_getBasysjSsxx_inXML);
        System.out.println("getBasysjSsxx.result=" + _getBasysjSsxx__return);


        }
        {
        System.out.println("Invoking getLisListHisToLisKsdm...");
        String _getLisListHisToLisKsdm_inXML = "";
        String _getLisListHisToLisKsdm__return = port.getLisListHisToLisKsdm(_getLisListHisToLisKsdm_inXML);
        System.out.println("getLisListHisToLisKsdm.result=" + _getLisListHisToLisKsdm__return);


        }
        {
        System.out.println("Invoking getZyBlnr...");
        String _getZyBlnr_inXML = "";
        String _getZyBlnr__return = port.getZyBlnr(_getZyBlnr_inXML);
        System.out.println("getZyBlnr.result=" + _getZyBlnr__return);


        }
        {
        System.out.println("Invoking getZyBrxxKsdm...");
        String _getZyBrxxKsdm_inXML = "";
        String _getZyBrxxKsdm__return = port.getZyBrxxKsdm(_getZyBrxxKsdm_inXML);
        System.out.println("getZyBrxxKsdm.result=" + _getZyBrxxKsdm__return);


        }
        {
        System.out.println("Invoking getMzjcYysq...");
        String _getMzjcYysq_inXML = "";
        String _getMzjcYysq__return = port.getMzjcYysq(_getMzjcYysq_inXML);
        System.out.println("getMzjcYysq.result=" + _getMzjcYysq__return);


        }
        {
        System.out.println("Invoking getMzTmbh...");
        String _getMzTmbh_inXML = "";
        String _getMzTmbh__return = port.getMzTmbh(_getMzTmbh_inXML);
        System.out.println("getMzTmbh.result=" + _getMzTmbh__return);


        }
        {
        System.out.println("Invoking szCaValidSign1...");
        String _szCaValidSign1_asPubkey = "";
        String _szCaValidSign1_asQmjg = "";
        String _szCaValidSign1_asQmyw = "";
        String _szCaValidSign1_inXML = "";
        Image _szCaValidSign1_imimage = null;
        String _szCaValidSign1__return = port.szCaValidSign1(_szCaValidSign1_asPubkey, _szCaValidSign1_asQmjg, _szCaValidSign1_asQmyw, _szCaValidSign1_inXML, _szCaValidSign1_imimage);
        System.out.println("szCaValidSign1.result=" + _szCaValidSign1__return);


        }
        {
        System.out.println("Invoking getChuFangList...");
        String _getChuFangList_inXML = "";
        String _getChuFangList__return = port.getChuFangList(_getChuFangList_inXML);
        System.out.println("getChuFangList.result=" + _getChuFangList__return);


        }
        {
        System.out.println("Invoking lisGetCTSpecimen...");
        String _lisGetCTSpecimen_inXML = "";
        String _lisGetCTSpecimen__return = port.lisGetCTSpecimen(_lisGetCTSpecimen_inXML);
        System.out.println("lisGetCTSpecimen.result=" + _lisGetCTSpecimen__return);


        }
        {
        System.out.println("Invoking getZybrSmtzForAll...");
        String _getZybrSmtzForAll_inXML = "";
        String _getZybrSmtzForAll__return = port.getZybrSmtzForAll(_getZybrSmtzForAll_inXML);
        System.out.println("getZybrSmtzForAll.result=" + _getZybrSmtzForAll__return);


        }
        {
        System.out.println("Invoking getChuFangListNyKfrq...");
        String _getChuFangListNyKfrq_inXML = "";
        String _getChuFangListNyKfrq__return = port.getChuFangListNyKfrq(_getChuFangListNyKfrq_inXML);
        System.out.println("getChuFangListNyKfrq.result=" + _getChuFangListNyKfrq__return);


        }
        {
        System.out.println("Invoking mzybMzdj...");
        String _mzybMzdj_inXML = "";
        String _mzybMzdj__return = port.mzybMzdj(_mzybMzdj_inXML);
        System.out.println("mzybMzdj.result=" + _mzybMzdj__return);


        }
        {
        System.out.println("Invoking dzMlMu002...");
        String _dzMlMu002_inXML = "";
        String _dzMlMu002__return = port.dzMlMu002(_dzMlMu002_inXML);
        System.out.println("dzMlMu002.result=" + _dzMlMu002__return);


        }
        {
        System.out.println("Invoking getSsdmList...");
        String _getSsdmList_inXML = "";
        String _getSsdmList__return = port.getSsdmList(_getSsdmList_inXML);
        System.out.println("getSsdmList.result=" + _getSsdmList__return);


        }
        {
        System.out.println("Invoking lisGetResultInfo...");
        String _lisGetResultInfo_inXML = "";
        String _lisGetResultInfo__return = port.lisGetResultInfo(_lisGetResultInfo_inXML);
        System.out.println("lisGetResultInfo.result=" + _lisGetResultInfo__return);


        }
        {
        System.out.println("Invoking dzMlMu001...");
        String _dzMlMu001_inXML = "";
        String _dzMlMu001__return = port.dzMlMu001(_dzMlMu001_inXML);
        System.out.println("dzMlMu001.result=" + _dzMlMu001__return);


        }
        {
        System.out.println("Invoking medRepeatedUse...");
        String _medRepeatedUse_inXML = "";
        String _medRepeatedUse__return = port.medRepeatedUse(_medRepeatedUse_inXML);
        System.out.println("medRepeatedUse.result=" + _medRepeatedUse__return);


        }
        {
        System.out.println("Invoking dzMlMu003...");
        String _dzMlMu003_inXML = "";
        String _dzMlMu003__return = port.dzMlMu003(_dzMlMu003_inXML);
        System.out.println("dzMlMu003.result=" + _dzMlMu003__return);


        }
        {
        System.out.println("Invoking getChuFangMx...");
        String _getChuFangMx_inXML = "";
        String _getChuFangMx__return = port.getChuFangMx(_getChuFangMx_inXML);
        System.out.println("getChuFangMx.result=" + _getChuFangMx__return);


        }
        {
        System.out.println("Invoking getITFPatChangeSpecIp...");
        String _getITFPatChangeSpecIp_inXML = "";
        String _getITFPatChangeSpecIp__return = port.getITFPatChangeSpecIp(_getITFPatChangeSpecIp_inXML);
        System.out.println("getITFPatChangeSpecIp.result=" + _getITFPatChangeSpecIp__return);


        }
        {
        System.out.println("Invoking getZyBqyz...");
        String _getZyBqyz_inXML = "";
        String _getZyBqyz__return = port.getZyBqyz(_getZyBqyz_inXML);
        System.out.println("getZyBqyz.result=" + _getZyBqyz__return);


        }
        {
        System.out.println("Invoking getBqhyYzdm...");
        String _getBqhyYzdm_inXML = "";
        String _getBqhyYzdm__return = port.getBqhyYzdm(_getBqhyYzdm_inXML);
        System.out.println("getBqhyYzdm.result=" + _getBqhyYzdm__return);


        }
        {
        System.out.println("Invoking getITFPrescibeOp...");
        String _getITFPrescibeOp_inXML = "";
        String _getITFPrescibeOp__return = port.getITFPrescibeOp(_getITFPrescibeOp_inXML);
        System.out.println("getITFPrescibeOp.result=" + _getITFPrescibeOp__return);


        }
        {
        System.out.println("Invoking getITFEmployeeSpec...");
        String _getITFEmployeeSpec__return = port.getITFEmployeeSpec();
        System.out.println("getITFEmployeeSpec.result=" + _getITFEmployeeSpec__return);


        }
        {
        System.out.println("Invoking getBqgyByJzwz...");
        String _getBqgyByJzwz_inXML = "";
        String _getBqgyByJzwz__return = port.getBqgyByJzwz(_getBqgyByJzwz_inXML);
        System.out.println("getBqgyByJzwz.result=" + _getBqgyByJzwz__return);


        }
        {
        System.out.println("Invoking getITFPatOtApplyIp...");
        String _getITFPatOtApplyIp_inXML = "";
        String _getITFPatOtApplyIp__return = port.getITFPatOtApplyIp(_getITFPatOtApplyIp_inXML);
        System.out.println("getITFPatOtApplyIp.result=" + _getITFPatOtApplyIp__return);


        }
        {
        System.out.println("Invoking getMzjcYysqSqdxh...");
        String _getMzjcYysqSqdxh_inXML = "";
        String _getMzjcYysqSqdxh__return = port.getMzjcYysqSqdxh(_getMzjcYysqSqdxh_inXML);
        System.out.println("getMzjcYysqSqdxh.result=" + _getMzjcYysqSqdxh__return);


        }
        {
        System.out.println("Invoking getZyFymx...");
        String _getZyFymx_inXML = "";
        String _getZyFymx__return = port.getZyFymx(_getZyFymx_inXML);
        System.out.println("getZyFymx.result=" + _getZyFymx__return);


        }
        {
        System.out.println("Invoking getITFAllergyOp...");
        String _getITFAllergyOp_inXML = "";
        String _getITFAllergyOp__return = port.getITFAllergyOp(_getITFAllergyOp_inXML);
        System.out.println("getITFAllergyOp.result=" + _getITFAllergyOp__return);


        }
        {
        System.out.println("Invoking ssGetReportInfoZy...");
        String _ssGetReportInfoZy_inXML = "";
        String _ssGetReportInfoZy__return = port.ssGetReportInfoZy(_ssGetReportInfoZy_inXML);
        System.out.println("ssGetReportInfoZy.result=" + _ssGetReportInfoZy__return);


        }
        {
        System.out.println("Invoking checkCTMRCancelStatus...");
        String _checkCTMRCancelStatus_inXML = "";
        String _checkCTMRCancelStatus__return = port.checkCTMRCancelStatus(_checkCTMRCancelStatus_inXML);
        System.out.println("checkCTMRCancelStatus.result=" + _checkCTMRCancelStatus__return);


        }
        {
        System.out.println("Invoking createJzhm...");
        String _createJzhm_inXML = "";
        String _createJzhm__return = port.createJzhm(_createJzhm_inXML);
        System.out.println("createJzhm.result=" + _createJzhm__return);


        }

        System.exit(0);
    }

}
