package com.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-26T10:07:47.068+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://webservice.test.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://webservice.test.com/HelloWorld/sayHiRequest", output = "http://webservice.test.com/HelloWorld/sayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHiResponse")
    public String sayHi(
            @WebParam(name = "text", targetNamespace = "")
            String text
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://webservice.test.com/HelloWorld/SayHiToUserListRequest", output = "http://webservice.test.com/HelloWorld/SayHiToUserListResponse")
    @RequestWrapper(localName = "SayHiToUserList", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHiToUserList")
    @WebMethod(operationName = "SayHiToUserList")
    @ResponseWrapper(localName = "SayHiToUserListResponse", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHiToUserListResponse")
    public java.util.List<String> sayHiToUserList(
            @WebParam(name = "arg0", targetNamespace = "")
            java.util.List<com.test.client.User> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://webservice.test.com/HelloWorld/sayHiToUserRequest", output = "http://webservice.test.com/HelloWorld/sayHiToUserResponse")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHiToUser")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://webservice.test.com/", className = "com.test.client.SayHiToUserResponse")
    public String sayHiToUser(
            @WebParam(name = "arg0", targetNamespace = "")
            com.test.client.User arg0
    );
}
